### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Use Cases of NumPy in Algo Trading

NumPy is an essential library for algorithmic trading due to its efficiency in numerical computations and array manipulations. Here are some key use cases of NumPy in algo trading:

1. **Data Preparation and Cleaning**
   - **Data Transformation:** Convert raw trading data into structured formats for analysis.
     ```python
     import numpy as np
     raw_data = [[100, '2023-06-01'], [102, '2023-06-02'], [104, '2023-06-03']]
     structured_data = np.array(raw_data, dtype=[('price', 'f4'), ('date', 'U10')])
     print(structured_data)
     ```
   - **Handling Missing Values:** Fill or interpolate missing data points in price series.
     ```python
     prices = np.array([100, 102, np.nan, 105])
     cleaned_prices = np.where(np.isnan(prices), np.nanmean(prices), prices)
     print(cleaned_prices)
     ```

2. **Technical Analysis**
   - **Calculating Indicators:** Compute moving averages, Bollinger Bands, RSI, etc.
     ```python
     prices = np.array([100, 102, 104, 103, 105, 107])
     window = 3
     moving_avg = np.convolve(prices, np.ones(window)/window, mode='valid')
     print(moving_avg)
     ```
   - **Trend Analysis:** Detect trends and patterns in price movements.
     ```python
     prices = np.array([100, 101, 102, 103, 104, 105])
     gradient = np.gradient(prices)
     print(gradient)
     ```

3. **Portfolio Management**
   - **Risk Assessment:** Calculate covariance matrices and perform risk analysis.
     ```python
     returns = np.array([[0.01, 0.02, -0.01], [0.03, 0.01, 0.02], [0.01, -0.02, 0.03]])
     cov_matrix = np.cov(returns, rowvar=False)
     print(cov_matrix)
     ```
   - **Optimization:** Use linear algebra to find the optimal portfolio weights.
     ```python
     import numpy.linalg as la
     returns = np.array([[0.01, 0.02], [0.03, 0.01], [0.01, -0.02]])
     mean_returns = np.mean(returns, axis=0)
     cov_matrix = np.cov(returns, rowvar=False)
     weights = la.solve(cov_matrix, mean_returns)
     weights /= np.sum(weights)
     print(weights)
     ```

4. **Statistical Analysis**
   - **Simulating Price Paths:** Generate synthetic price data for backtesting.
     ```python
     np.random.seed(42)
     n_steps = 1000
     steps = np.random.choice([-1, 1], size=n_steps)
     random_walk = np.cumsum(steps)
     print(random_walk)
     ```
   - **Hypothesis Testing:** Perform statistical tests to validate trading strategies.
     ```python
     from scipy import stats
     returns = np.array([0.01, 0.02, -0.01, 0.03, -0.02])
     t_stat, p_value = stats.ttest_1samp(returns, 0)
     print(t_stat, p_value)
     ```

5. **Performance Measurement**
   - **Sharpe Ratio Calculation:** Measure risk-adjusted returns.
     ```python
     returns = np.array([0.01, 0.02, -0.01, 0.03, -0.02])
     risk_free_rate = 0.01
     sharpe_ratio = (np.mean(returns) - risk_free_rate) / np.std(returns)
     print(sharpe_ratio)
     ```
   - **Drawdown Analysis:** Identify and analyze maximum drawdowns in the portfolio.
     ```python
     prices = np.array([100, 110, 105, 115, 108])
     peak = np.maximum.accumulate(prices)
     drawdown = (prices - peak) / peak
     max_drawdown = np.min(drawdown)
     print(max_drawdown)
     ```






### Creating Numpy Arrays

In [ ]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((3,4))

array([[0.85721156, 0.31248316, 0.08807828, 0.35230774],
       [0.96813914, 0.44681708, 0.56396358, 0.53020065],
       [0.03277116, 0.28543753, 0.09521082, 0.87967034]])

In [ ]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim
a3.ndim

3

In [ ]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# itemsize
a3.itemsize

8

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[43., 28., 71.],
       [27., 93., 36.],
       [31., 18.,  7.]])

In [ ]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([35991., 46872., 17892.])

In [ ]:
# mean/median/std/var
np.var(a1,axis=1)

array([317.55555556, 854.        ,  96.22222222])

In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[-0.83177474,  0.27090579,  0.95105465],
       [ 0.95637593, -0.94828214, -0.99177885],
       [-0.40403765, -0.75098725,  0.6569866 ]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.exp(a1)

array([[4.72783947e+18, 1.44625706e+12, 6.83767123e+30],
       [5.32048241e+11, 2.45124554e+40, 4.31123155e+15],
       [2.90488497e+13, 6.56599691e+07, 1.09663316e+03]])

In [ ]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[48.,  4.,  6.],
       [ 3., 18., 82.]])

### Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,0]

4

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

5

In [ ]:
a3[1,1,0]

6

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [ ]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape

In [ ]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [ ]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,5)

ValueError: ignored

In [ ]:
# vertical splitting

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(a5,2)

ValueError: ignored