In [1]:
import pandas as pd
import numpy as np

In [2]:
A = [[1,2],[3,4]]
B = [[5,6],[7,8]]

A_arr = np.array(A)
B_arr = np.array(B)

In [3]:
A

[[1, 2], [3, 4]]

In [4]:
B

[[5, 6], [7, 8]]

In [5]:
A_arr

array([[1, 2],
       [3, 4]])

In [6]:
B_arr

array([[5, 6],
       [7, 8]])

In [7]:
#1 Addition 
C = A_arr+B_arr
C

array([[ 6,  8],
       [10, 12]])

In [8]:
#2 Subtraction
C = A_arr - B_arr
C

array([[-4, -4],
       [-4, -4]])

In [9]:
#3 Dot product
np.dot(A_arr,B_arr)

array([[19, 22],
       [43, 50]])