### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [38]:
# code
import numpy as np

ohlc1 = np.array(
    [300.1, 101.5, 499.5, 101.0,901.3, 802.9, 650.5, 701.8,211.8, 103.0, 331.0, 502.5]
)

ohlc2 = np.array([
    [910.0, 201.5, 599.5, 301.0],
    [841.0, 402.0, 910.5, 501.8],
    [721.8, 503.0, 101.0, 782.5],
    [501.8, 903.0, 841.0, 902.5]
])

np.sort(ohlc1)[::-1]

array([901.3, 802.9, 701.8, 650.5, 502.5, 499.5, 331. , 300.1, 211.8,
       103. , 101.5, 101. ])

In [16]:
np.sort(ohlc2, axis=1)

array([[201.5, 301. , 599.5, 910. ],
       [402. , 501.8, 841. , 910.5],
       [101. , 503. , 721.8, 782.5],
       [501.8, 841. , 902.5, 903. ]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code
ohlc1 = np.array(
    [300.1, 101.5, 499.5, 101.0,901.3, 802.9, 650.5, 701.8,211.8, 103.0, 331.0, 502.5]
)

ohlc2 = np.array([
    [910.0, 201.5, 599.5, 301.0],
    [841.0, 402.0, 910.5, 501.8],
    [721.8, 503.0, 101.0, 782.5],
    [501.8, 903.0, 841.0, 902.5]
])

In [17]:
np.append(ohlc1,500)

array([300.1, 101.5, 499.5, 101. , 901.3, 802.9, 650.5, 701.8, 211.8,
       103. , 331. , 502.5, 500. ])

In [19]:
np.append(ohlc2,np.arange(4).reshape(4,1),axis=1)

array([[910. , 201.5, 599.5, 301. ,   0. ],
       [841. , 402. , 910.5, 501.8,   1. ],
       [721.8, 503. , 101. , 782.5,   2. ],
       [501.8, 903. , 841. , 902.5,   3. ]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [25]:
# code
c = np.arange(12).reshape(4,3)
d = np.arange(12,24).reshape(4,3)


print(c)
print(d)
np.concatenate((c,d),axis=0)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [26]:
# code
e = np.array([1,1,1,2,2,2,3,3,3,4,4,4,55,5,6,7,8,8])
np.unique(e)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 55])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [32]:
# code
ohlc1.shape
f  =np.expand_dims(ohlc1,axis=0)
f

array([[300.1, 101.5, 499.5, 101. , 901.3, 802.9, 650.5, 701.8, 211.8,
        103. , 331. , 502.5]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [36]:
ohlc1
print(np.where(ohlc1>400.0))
print(ohlc1)

(array([ 2,  4,  5,  6,  7, 11]),)
[300.1 101.5 499.5 101.  901.3 802.9 650.5 701.8 211.8 103.  331.  502.5]


In [ ]:
# find all indices with value greater than 400


In [37]:
# replace all values > 400 with 0
np.where(ohlc1>400.0,0,ohlc1)

array([300.1, 101.5,   0. , 101. ,   0. ,   0. ,   0. ,   0. , 211.8,
       103. , 331. ,   0. ])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [39]:
# code
ohlc1

array([300.1, 101.5, 499.5, 101. , 901.3, 802.9, 650.5, 701.8, 211.8,
       103. , 331. , 502.5])

In [40]:
np.argmax(ohlc1)

4

In [41]:
np.argmin(ohlc1)

3

In [ ]:
# np.argmin


### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [42]:
ohlc1

array([300.1, 101.5, 499.5, 101. , 901.3, 802.9, 650.5, 701.8, 211.8,
       103. , 331. , 502.5])

In [43]:
np.cumsum(ohlc1)

array([ 300.1,  401.6,  901.1, 1002.1, 1903.4, 2706.3, 3356.8, 4058.6,
       4270.4, 4373.4, 4704.4, 5206.9])

In [44]:
# np.cumprod
np.cumprod(ohlc1)

array([3.00100000e+02, 3.04601500e+04, 1.52148449e+07, 1.53669934e+09,
       1.38502711e+12, 1.11203827e+15, 7.23380894e+17, 5.07668711e+20,
       1.07524233e+23, 1.10749960e+25, 3.66582368e+27, 1.84207640e+30])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [45]:
ohlc1

array([300.1, 101.5, 499.5, 101. , 901.3, 802.9, 650.5, 701.8, 211.8,
       103. , 331. , 502.5])

In [48]:
np.percentile(ohlc1,50)

415.25

In [49]:
np.median(ohlc1)

415.25

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [55]:
# code
ohlc1

array([300.1, 101.5, 499.5, 101. , 901.3, 802.9, 650.5, 701.8, 211.8,
       103. , 331. , 502.5])

In [56]:
np.histogram(ohlc1,bins=[0,300,600,999])

(array([4, 4, 4]), array([  0, 300, 600, 999]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [63]:
a = np.array([111,222,333,111,222,333])
b = np.array([0,20,-1,300,200,1000])

np.corrcoef(a,b)

array([[1.        , 0.40469152],
       [0.40469152, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [77]:
# code
ohlc1
items = [101. , 901.3, 802.9, 650.5]

array([300.1, 101.5, 499.5, 101. , 901.3, 802.9, 650.5, 701.8, 211.8,
       103. , 331. , 502.5])

In [79]:
ohlc1[np.isin(ohlc1,300.1)]

array([300.1])

In [80]:
# code
ohlc1[np.isin(ohlc1,items)]

array([300.1, 101.5, 499.5, 101. ])

In [ ]:
# code


In [ ]:
# code


In [ ]:
# code
